// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_action_type_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CargoWallActionType int32

const (
	CargoWallActionType_CARGO_WALL_ACTION_TYPE_UNSPECIFIED CargoWallActionType = 0
	CargoWallActionType_CARGO_WALL_ACTION_TYPE_ALLOW       CargoWallActionType = 1
	CargoWallActionType_CARGO_WALL_ACTION_TYPE_DENY        CargoWallActionType = 2
)

// Enum value maps for CargoWallActionType.
var (
	CargoWallActionType_name = map[int32]string{
		0: "CARGO_WALL_ACTION_TYPE_UNSPECIFIED",
		1: "CARGO_WALL_ACTION_TYPE_ALLOW",
		2: "CARGO_WALL_ACTION_TYPE_DENY",
	}
	CargoWallActionType_value = map[string]int32{
		"CARGO_WALL_ACTION_TYPE_UNSPECIFIED": 0,
		"CARGO_WALL_ACTION_TYPE_ALLOW":       1,
		"CARGO_WALL_ACTION_TYPE_DENY":        2,
	}
)

func (x CargoWallActionType) Enum() *CargoWallActionType {
	p := new(CargoWallActionType)
	*p = x
	return p
}

func (x CargoWallActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_action_type_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallActionType) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_action_type_enum_proto_enumTypes[0]
}

func (x CargoWallActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallActionType.Descriptor instead.
func (CargoWallActionType) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_action_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_action_type_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_action_type_enum_proto_rawDesc = "" +
	"\n" +
	"&data/cargo_wall_action_type_enum.proto\x12\x11grpc.cargowall.v1*\x80\x01\n" +
	"\x13CargoWallActionType\x12&\n" +
	"\"CARGO_WALL_ACTION_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCARGO_WALL_ACTION_TYPE_ALLOW\x10\x01\x12\x1f\n" +
	"\x1bCARGO_WALL_ACTION_TYPE_DENY\x10\x02BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_action_type_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_action_type_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_action_type_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_action_type_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_action_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_action_type_enum_proto_rawDesc), len(file_data_cargo_wall_action_type_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_action_type_enum_proto_rawDescData
}

var file_data_cargo_wall_action_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_action_type_enum_proto_goTypes = []any{
	(CargoWallActionType)(0), // 0: grpc.cargowall.v1.CargoWallActionType
}
var file_data_cargo_wall_action_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_action_type_enum_proto_init() }
func file_data_cargo_wall_action_type_enum_proto_init() {
	if File_data_cargo_wall_action_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_action_type_enum_proto_rawDesc), len(file_data_cargo_wall_action_type_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_action_type_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_action_type_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_action_type_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_action_type_enum_proto = out.File
	file_data_cargo_wall_action_type_enum_proto_goTypes = nil
	file_data_cargo_wall_action_type_enum_proto_depIdxs = nil
}
