// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_auto_allowed_type_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CargoWallAutoAllowedType int32

const (
	CargoWallAutoAllowedType_CARGO_WALL_AUTO_ALLOWED_TYPE_UNSPECIFIED          CargoWallAutoAllowedType = 0
	CargoWallAutoAllowedType_CARGO_WALL_AUTO_ALLOWED_TYPE_CODECARGO            CargoWallAutoAllowedType = 1
	CargoWallAutoAllowedType_CARGO_WALL_AUTO_ALLOWED_TYPE_DNS                  CargoWallAutoAllowedType = 2
	CargoWallAutoAllowedType_CARGO_WALL_AUTO_ALLOWED_TYPE_AZURE_INFRASTRUCTURE CargoWallAutoAllowedType = 3
	CargoWallAutoAllowedType_CARGO_WALL_AUTO_ALLOWED_TYPE_GITHUB_SERVICE       CargoWallAutoAllowedType = 4
)

// Enum value maps for CargoWallAutoAllowedType.
var (
	CargoWallAutoAllowedType_name = map[int32]string{
		0: "CARGO_WALL_AUTO_ALLOWED_TYPE_UNSPECIFIED",
		1: "CARGO_WALL_AUTO_ALLOWED_TYPE_CODECARGO",
		2: "CARGO_WALL_AUTO_ALLOWED_TYPE_DNS",
		3: "CARGO_WALL_AUTO_ALLOWED_TYPE_AZURE_INFRASTRUCTURE",
		4: "CARGO_WALL_AUTO_ALLOWED_TYPE_GITHUB_SERVICE",
	}
	CargoWallAutoAllowedType_value = map[string]int32{
		"CARGO_WALL_AUTO_ALLOWED_TYPE_UNSPECIFIED":          0,
		"CARGO_WALL_AUTO_ALLOWED_TYPE_CODECARGO":            1,
		"CARGO_WALL_AUTO_ALLOWED_TYPE_DNS":                  2,
		"CARGO_WALL_AUTO_ALLOWED_TYPE_AZURE_INFRASTRUCTURE": 3,
		"CARGO_WALL_AUTO_ALLOWED_TYPE_GITHUB_SERVICE":       4,
	}
)

func (x CargoWallAutoAllowedType) Enum() *CargoWallAutoAllowedType {
	p := new(CargoWallAutoAllowedType)
	*p = x
	return p
}

func (x CargoWallAutoAllowedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallAutoAllowedType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_auto_allowed_type_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallAutoAllowedType) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_auto_allowed_type_enum_proto_enumTypes[0]
}

func (x CargoWallAutoAllowedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallAutoAllowedType.Descriptor instead.
func (CargoWallAutoAllowedType) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_auto_allowed_type_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_auto_allowed_type_enum_proto_rawDesc = "" +
	"\n" +
	",data/cargo_wall_auto_allowed_type_enum.proto\x12\x11grpc.cargowall.v1*\x82\x02\n" +
	"\x18CargoWallAutoAllowedType\x12,\n" +
	"(CARGO_WALL_AUTO_ALLOWED_TYPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&CARGO_WALL_AUTO_ALLOWED_TYPE_CODECARGO\x10\x01\x12$\n" +
	" CARGO_WALL_AUTO_ALLOWED_TYPE_DNS\x10\x02\x125\n" +
	"1CARGO_WALL_AUTO_ALLOWED_TYPE_AZURE_INFRASTRUCTURE\x10\x03\x12/\n" +
	"+CARGO_WALL_AUTO_ALLOWED_TYPE_GITHUB_SERVICE\x10\x04BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_auto_allowed_type_enum_proto_rawDesc), len(file_data_cargo_wall_auto_allowed_type_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_auto_allowed_type_enum_proto_rawDescData
}

var file_data_cargo_wall_auto_allowed_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_auto_allowed_type_enum_proto_goTypes = []any{
	(CargoWallAutoAllowedType)(0), // 0: grpc.cargowall.v1.CargoWallAutoAllowedType
}
var file_data_cargo_wall_auto_allowed_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_auto_allowed_type_enum_proto_init() }
func file_data_cargo_wall_auto_allowed_type_enum_proto_init() {
	if File_data_cargo_wall_auto_allowed_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_auto_allowed_type_enum_proto_rawDesc), len(file_data_cargo_wall_auto_allowed_type_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_auto_allowed_type_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_auto_allowed_type_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_auto_allowed_type_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_auto_allowed_type_enum_proto = out.File
	file_data_cargo_wall_auto_allowed_type_enum_proto_goTypes = nil
	file_data_cargo_wall_auto_allowed_type_enum_proto_depIdxs = nil
}
