// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_protocol_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
type CargoWallProtocol int32

const (
	CargoWallProtocol_CARGO_WALL_PROTOCOL_ALL CargoWallProtocol = 0
	CargoWallProtocol_CARGO_WALL_PROTOCOL_TCP CargoWallProtocol = 6
	CargoWallProtocol_CARGO_WALL_PROTOCOL_UDP CargoWallProtocol = 17
)

// Enum value maps for CargoWallProtocol.
var (
	CargoWallProtocol_name = map[int32]string{
		0:  "CARGO_WALL_PROTOCOL_ALL",
		6:  "CARGO_WALL_PROTOCOL_TCP",
		17: "CARGO_WALL_PROTOCOL_UDP",
	}
	CargoWallProtocol_value = map[string]int32{
		"CARGO_WALL_PROTOCOL_ALL": 0,
		"CARGO_WALL_PROTOCOL_TCP": 6,
		"CARGO_WALL_PROTOCOL_UDP": 17,
	}
)

func (x CargoWallProtocol) Enum() *CargoWallProtocol {
	p := new(CargoWallProtocol)
	*p = x
	return p
}

func (x CargoWallProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_protocol_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallProtocol) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_protocol_enum_proto_enumTypes[0]
}

func (x CargoWallProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallProtocol.Descriptor instead.
func (CargoWallProtocol) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_protocol_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_protocol_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_protocol_enum_proto_rawDesc = "" +
	"\n" +
	"#data/cargo_wall_protocol_enum.proto\x12\x11grpc.cargowall.v1*j\n" +
	"\x11CargoWallProtocol\x12\x1b\n" +
	"\x17CARGO_WALL_PROTOCOL_ALL\x10\x00\x12\x1b\n" +
	"\x17CARGO_WALL_PROTOCOL_TCP\x10\x06\x12\x1b\n" +
	"\x17CARGO_WALL_PROTOCOL_UDP\x10\x11BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_protocol_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_protocol_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_protocol_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_protocol_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_protocol_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_protocol_enum_proto_rawDesc), len(file_data_cargo_wall_protocol_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_protocol_enum_proto_rawDescData
}

var file_data_cargo_wall_protocol_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_protocol_enum_proto_goTypes = []any{
	(CargoWallProtocol)(0), // 0: grpc.cargowall.v1.CargoWallProtocol
}
var file_data_cargo_wall_protocol_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_protocol_enum_proto_init() }
func file_data_cargo_wall_protocol_enum_proto_init() {
	if File_data_cargo_wall_protocol_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_protocol_enum_proto_rawDesc), len(file_data_cargo_wall_protocol_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_protocol_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_protocol_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_protocol_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_protocol_enum_proto = out.File
	file_data_cargo_wall_protocol_enum_proto_goTypes = nil
	file_data_cargo_wall_protocol_enum_proto_depIdxs = nil
}
