// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_rule_type_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CargoWallRuleType int32

const (
	CargoWallRuleType_CARGO_WALL_RULE_TYPE_UNSPECIFIED CargoWallRuleType = 0
	CargoWallRuleType_CARGO_WALL_RULE_TYPE_CIDR        CargoWallRuleType = 1
	CargoWallRuleType_CARGO_WALL_RULE_TYPE_HOSTNAME    CargoWallRuleType = 2
)

// Enum value maps for CargoWallRuleType.
var (
	CargoWallRuleType_name = map[int32]string{
		0: "CARGO_WALL_RULE_TYPE_UNSPECIFIED",
		1: "CARGO_WALL_RULE_TYPE_CIDR",
		2: "CARGO_WALL_RULE_TYPE_HOSTNAME",
	}
	CargoWallRuleType_value = map[string]int32{
		"CARGO_WALL_RULE_TYPE_UNSPECIFIED": 0,
		"CARGO_WALL_RULE_TYPE_CIDR":        1,
		"CARGO_WALL_RULE_TYPE_HOSTNAME":    2,
	}
)

func (x CargoWallRuleType) Enum() *CargoWallRuleType {
	p := new(CargoWallRuleType)
	*p = x
	return p
}

func (x CargoWallRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_rule_type_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallRuleType) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_rule_type_enum_proto_enumTypes[0]
}

func (x CargoWallRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallRuleType.Descriptor instead.
func (CargoWallRuleType) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_rule_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_rule_type_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_rule_type_enum_proto_rawDesc = "" +
	"\n" +
	"$data/cargo_wall_rule_type_enum.proto\x12\x11grpc.cargowall.v1*{\n" +
	"\x11CargoWallRuleType\x12$\n" +
	" CARGO_WALL_RULE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CARGO_WALL_RULE_TYPE_CIDR\x10\x01\x12!\n" +
	"\x1dCARGO_WALL_RULE_TYPE_HOSTNAME\x10\x02BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_rule_type_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_rule_type_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_rule_type_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_rule_type_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_rule_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_rule_type_enum_proto_rawDesc), len(file_data_cargo_wall_rule_type_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_rule_type_enum_proto_rawDescData
}

var file_data_cargo_wall_rule_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_rule_type_enum_proto_goTypes = []any{
	(CargoWallRuleType)(0), // 0: grpc.cargowall.v1.CargoWallRuleType
}
var file_data_cargo_wall_rule_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_rule_type_enum_proto_init() }
func file_data_cargo_wall_rule_type_enum_proto_init() {
	if File_data_cargo_wall_rule_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_rule_type_enum_proto_rawDesc), len(file_data_cargo_wall_rule_type_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_rule_type_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_rule_type_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_rule_type_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_rule_type_enum_proto = out.File
	file_data_cargo_wall_rule_type_enum_proto_goTypes = nil
	file_data_cargo_wall_rule_type_enum_proto_depIdxs = nil
}
