// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_fetch_failure_class_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Why the policy could not be retrieved. Only genuine retrieval failures
// appear here by construction: authoritative answers (404 not-onboarded,
// 401/403 bad token, 400 inactive repository) never change posture and so
// never produce a downgrade record.
type CargoWallFetchFailureClass int32

const (
	CargoWallFetchFailureClass_CARGO_WALL_FETCH_FAILURE_CLASS_UNSPECIFIED CargoWallFetchFailureClass = 0
	// No HTTP response: connect/timeout/body-read failure.
	CargoWallFetchFailureClass_CARGO_WALL_FETCH_FAILURE_CLASS_TRANSPORT CargoWallFetchFailureClass = 1
	// Server-side failure: 5xx, 429, or an unexpected status.
	CargoWallFetchFailureClass_CARGO_WALL_FETCH_FAILURE_CLASS_SERVER CargoWallFetchFailureClass = 2
	// The response could not be parsed or loaded as a policy.
	CargoWallFetchFailureClass_CARGO_WALL_FETCH_FAILURE_CLASS_MALFORMED CargoWallFetchFailureClass = 3
)

// Enum value maps for CargoWallFetchFailureClass.
var (
	CargoWallFetchFailureClass_name = map[int32]string{
		0: "CARGO_WALL_FETCH_FAILURE_CLASS_UNSPECIFIED",
		1: "CARGO_WALL_FETCH_FAILURE_CLASS_TRANSPORT",
		2: "CARGO_WALL_FETCH_FAILURE_CLASS_SERVER",
		3: "CARGO_WALL_FETCH_FAILURE_CLASS_MALFORMED",
	}
	CargoWallFetchFailureClass_value = map[string]int32{
		"CARGO_WALL_FETCH_FAILURE_CLASS_UNSPECIFIED": 0,
		"CARGO_WALL_FETCH_FAILURE_CLASS_TRANSPORT":   1,
		"CARGO_WALL_FETCH_FAILURE_CLASS_SERVER":      2,
		"CARGO_WALL_FETCH_FAILURE_CLASS_MALFORMED":   3,
	}
)

func (x CargoWallFetchFailureClass) Enum() *CargoWallFetchFailureClass {
	p := new(CargoWallFetchFailureClass)
	*p = x
	return p
}

func (x CargoWallFetchFailureClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallFetchFailureClass) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_fetch_failure_class_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallFetchFailureClass) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_fetch_failure_class_enum_proto_enumTypes[0]
}

func (x CargoWallFetchFailureClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallFetchFailureClass.Descriptor instead.
func (CargoWallFetchFailureClass) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_fetch_failure_class_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_fetch_failure_class_enum_proto_rawDesc = "" +
	"\n" +
	".data/cargo_wall_fetch_failure_class_enum.proto\x12\x11grpc.cargowall.v1*\xd3\x01\n" +
	"\x1aCargoWallFetchFailureClass\x12.\n" +
	"*CARGO_WALL_FETCH_FAILURE_CLASS_UNSPECIFIED\x10\x00\x12,\n" +
	"(CARGO_WALL_FETCH_FAILURE_CLASS_TRANSPORT\x10\x01\x12)\n" +
	"%CARGO_WALL_FETCH_FAILURE_CLASS_SERVER\x10\x02\x12,\n" +
	"(CARGO_WALL_FETCH_FAILURE_CLASS_MALFORMED\x10\x03BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_fetch_failure_class_enum_proto_rawDesc), len(file_data_cargo_wall_fetch_failure_class_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_fetch_failure_class_enum_proto_rawDescData
}

var file_data_cargo_wall_fetch_failure_class_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_fetch_failure_class_enum_proto_goTypes = []any{
	(CargoWallFetchFailureClass)(0), // 0: grpc.cargowall.v1.CargoWallFetchFailureClass
}
var file_data_cargo_wall_fetch_failure_class_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_fetch_failure_class_enum_proto_init() }
func file_data_cargo_wall_fetch_failure_class_enum_proto_init() {
	if File_data_cargo_wall_fetch_failure_class_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_fetch_failure_class_enum_proto_rawDesc), len(file_data_cargo_wall_fetch_failure_class_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_fetch_failure_class_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_fetch_failure_class_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_fetch_failure_class_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_fetch_failure_class_enum_proto = out.File
	file_data_cargo_wall_fetch_failure_class_enum_proto_goTypes = nil
	file_data_cargo_wall_fetch_failure_class_enum_proto_depIdxs = nil
}
