// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/cargo_wall_downgrade_type_enum.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How a run's effective posture was downgraded from the requested one when
// the policy could not be retrieved (--api-failure-mode, cargowall#96).
type CargoWallDowngradeType int32

const (
	CargoWallDowngradeType_CARGO_WALL_DOWNGRADE_TYPE_UNSPECIFIED CargoWallDowngradeType = 0
	// --api-failure-mode=audit: enforcement downgraded to audit-only.
	CargoWallDowngradeType_CARGO_WALL_DOWNGRADE_TYPE_AUDIT_FALLBACK CargoWallDowngradeType = 1
	// --api-failure-mode=fail: run locked down to deny-all, ready withheld.
	CargoWallDowngradeType_CARGO_WALL_DOWNGRADE_TYPE_LOCKDOWN CargoWallDowngradeType = 2
	// Run enforced a cached last-known-good policy (cargowall#97).
	CargoWallDowngradeType_CARGO_WALL_DOWNGRADE_TYPE_CACHED_POLICY CargoWallDowngradeType = 3
)

// Enum value maps for CargoWallDowngradeType.
var (
	CargoWallDowngradeType_name = map[int32]string{
		0: "CARGO_WALL_DOWNGRADE_TYPE_UNSPECIFIED",
		1: "CARGO_WALL_DOWNGRADE_TYPE_AUDIT_FALLBACK",
		2: "CARGO_WALL_DOWNGRADE_TYPE_LOCKDOWN",
		3: "CARGO_WALL_DOWNGRADE_TYPE_CACHED_POLICY",
	}
	CargoWallDowngradeType_value = map[string]int32{
		"CARGO_WALL_DOWNGRADE_TYPE_UNSPECIFIED":    0,
		"CARGO_WALL_DOWNGRADE_TYPE_AUDIT_FALLBACK": 1,
		"CARGO_WALL_DOWNGRADE_TYPE_LOCKDOWN":       2,
		"CARGO_WALL_DOWNGRADE_TYPE_CACHED_POLICY":  3,
	}
)

func (x CargoWallDowngradeType) Enum() *CargoWallDowngradeType {
	p := new(CargoWallDowngradeType)
	*p = x
	return p
}

func (x CargoWallDowngradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CargoWallDowngradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_cargo_wall_downgrade_type_enum_proto_enumTypes[0].Descriptor()
}

func (CargoWallDowngradeType) Type() protoreflect.EnumType {
	return &file_data_cargo_wall_downgrade_type_enum_proto_enumTypes[0]
}

func (x CargoWallDowngradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CargoWallDowngradeType.Descriptor instead.
func (CargoWallDowngradeType) EnumDescriptor() ([]byte, []int) {
	return file_data_cargo_wall_downgrade_type_enum_proto_rawDescGZIP(), []int{0}
}

var File_data_cargo_wall_downgrade_type_enum_proto protoreflect.FileDescriptor

const file_data_cargo_wall_downgrade_type_enum_proto_rawDesc = "" +
	"\n" +
	")data/cargo_wall_downgrade_type_enum.proto\x12\x11grpc.cargowall.v1*\xc6\x01\n" +
	"\x16CargoWallDowngradeType\x12)\n" +
	"%CARGO_WALL_DOWNGRADE_TYPE_UNSPECIFIED\x10\x00\x12,\n" +
	"(CARGO_WALL_DOWNGRADE_TYPE_AUDIT_FALLBACK\x10\x01\x12&\n" +
	"\"CARGO_WALL_DOWNGRADE_TYPE_LOCKDOWN\x10\x02\x12+\n" +
	"'CARGO_WALL_DOWNGRADE_TYPE_CACHED_POLICY\x10\x03BXZ4github.com/code-cargo/cargowall/pb/cargowall/v1/data\xaa\x02\x1fController.Data.Pb.CargoWall.V1b\x06proto3"

var (
	file_data_cargo_wall_downgrade_type_enum_proto_rawDescOnce sync.Once
	file_data_cargo_wall_downgrade_type_enum_proto_rawDescData []byte
)

func file_data_cargo_wall_downgrade_type_enum_proto_rawDescGZIP() []byte {
	file_data_cargo_wall_downgrade_type_enum_proto_rawDescOnce.Do(func() {
		file_data_cargo_wall_downgrade_type_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_cargo_wall_downgrade_type_enum_proto_rawDesc), len(file_data_cargo_wall_downgrade_type_enum_proto_rawDesc)))
	})
	return file_data_cargo_wall_downgrade_type_enum_proto_rawDescData
}

var file_data_cargo_wall_downgrade_type_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_cargo_wall_downgrade_type_enum_proto_goTypes = []any{
	(CargoWallDowngradeType)(0), // 0: grpc.cargowall.v1.CargoWallDowngradeType
}
var file_data_cargo_wall_downgrade_type_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_cargo_wall_downgrade_type_enum_proto_init() }
func file_data_cargo_wall_downgrade_type_enum_proto_init() {
	if File_data_cargo_wall_downgrade_type_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_cargo_wall_downgrade_type_enum_proto_rawDesc), len(file_data_cargo_wall_downgrade_type_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_cargo_wall_downgrade_type_enum_proto_goTypes,
		DependencyIndexes: file_data_cargo_wall_downgrade_type_enum_proto_depIdxs,
		EnumInfos:         file_data_cargo_wall_downgrade_type_enum_proto_enumTypes,
	}.Build()
	File_data_cargo_wall_downgrade_type_enum_proto = out.File
	file_data_cargo_wall_downgrade_type_enum_proto_goTypes = nil
	file_data_cargo_wall_downgrade_type_enum_proto_depIdxs = nil
}
