// Code generated by mockery v2.53.3. DO NOT EDIT.

package firewall

import (
	config "github.com/code-cargo/cargowall/pkg/config"
	mock "github.com/stretchr/testify/mock"

	net "net"
)

// MockFirewall is an autogenerated mock type for the Firewall type
type MockFirewall struct {
	mock.Mock
}

type MockFirewall_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFirewall) EXPECT() *MockFirewall_Expecter {
	return &MockFirewall_Expecter{mock: &_m.Mock}
}

// AddIP provides a mock function with given fields: ip, action, ports
func (_m *MockFirewall) AddIP(ip net.IP, action config.Action, ports []config.Port) (bool, error) {
	ret := _m.Called(ip, action, ports)

	if len(ret) == 0 {
		panic("no return value specified for AddIP")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(net.IP, config.Action, []config.Port) (bool, error)); ok {
		return rf(ip, action, ports)
	}
	if rf, ok := ret.Get(0).(func(net.IP, config.Action, []config.Port) bool); ok {
		r0 = rf(ip, action, ports)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(net.IP, config.Action, []config.Port) error); ok {
		r1 = rf(ip, action, ports)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFirewall_AddIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddIP'
type MockFirewall_AddIP_Call struct {
	*mock.Call
}

// AddIP is a helper method to define mock.On call
//   - ip net.IP
//   - action config.Action
//   - ports []config.Port
func (_e *MockFirewall_Expecter) AddIP(ip interface{}, action interface{}, ports interface{}) *MockFirewall_AddIP_Call {
	return &MockFirewall_AddIP_Call{Call: _e.mock.On("AddIP", ip, action, ports)}
}

func (_c *MockFirewall_AddIP_Call) Run(run func(ip net.IP, action config.Action, ports []config.Port)) *MockFirewall_AddIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(net.IP), args[1].(config.Action), args[2].([]config.Port))
	})
	return _c
}

func (_c *MockFirewall_AddIP_Call) Return(_a0 bool, _a1 error) *MockFirewall_AddIP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFirewall_AddIP_Call) RunAndReturn(run func(net.IP, config.Action, []config.Port) (bool, error)) *MockFirewall_AddIP_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveIP provides a mock function with given fields: ip
func (_m *MockFirewall) RemoveIP(ip net.IP) error {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for RemoveIP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(net.IP) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFirewall_RemoveIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveIP'
type MockFirewall_RemoveIP_Call struct {
	*mock.Call
}

// RemoveIP is a helper method to define mock.On call
//   - ip net.IP
func (_e *MockFirewall_Expecter) RemoveIP(ip interface{}) *MockFirewall_RemoveIP_Call {
	return &MockFirewall_RemoveIP_Call{Call: _e.mock.On("RemoveIP", ip)}
}

func (_c *MockFirewall_RemoveIP_Call) Run(run func(ip net.IP)) *MockFirewall_RemoveIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(net.IP))
	})
	return _c
}

func (_c *MockFirewall_RemoveIP_Call) Return(_a0 error) *MockFirewall_RemoveIP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFirewall_RemoveIP_Call) RunAndReturn(run func(net.IP) error) *MockFirewall_RemoveIP_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuditMode provides a mock function with given fields: enabled
func (_m *MockFirewall) SetAuditMode(enabled bool) error {
	ret := _m.Called(enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetAuditMode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(enabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFirewall_SetAuditMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuditMode'
type MockFirewall_SetAuditMode_Call struct {
	*mock.Call
}

// SetAuditMode is a helper method to define mock.On call
//   - enabled bool
func (_e *MockFirewall_Expecter) SetAuditMode(enabled interface{}) *MockFirewall_SetAuditMode_Call {
	return &MockFirewall_SetAuditMode_Call{Call: _e.mock.On("SetAuditMode", enabled)}
}

func (_c *MockFirewall_SetAuditMode_Call) Run(run func(enabled bool)) *MockFirewall_SetAuditMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockFirewall_SetAuditMode_Call) Return(_a0 error) *MockFirewall_SetAuditMode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFirewall_SetAuditMode_Call) RunAndReturn(run func(bool) error) *MockFirewall_SetAuditMode_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaultAction provides a mock function with given fields: action
func (_m *MockFirewall) SetDefaultAction(action config.Action) error {
	ret := _m.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for SetDefaultAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Action) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFirewall_SetDefaultAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaultAction'
type MockFirewall_SetDefaultAction_Call struct {
	*mock.Call
}

// SetDefaultAction is a helper method to define mock.On call
//   - action config.Action
func (_e *MockFirewall_Expecter) SetDefaultAction(action interface{}) *MockFirewall_SetDefaultAction_Call {
	return &MockFirewall_SetDefaultAction_Call{Call: _e.mock.On("SetDefaultAction", action)}
}

func (_c *MockFirewall_SetDefaultAction_Call) Run(run func(action config.Action)) *MockFirewall_SetDefaultAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Action))
	})
	return _c
}

func (_c *MockFirewall_SetDefaultAction_Call) Return(_a0 error) *MockFirewall_SetDefaultAction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFirewall_SetDefaultAction_Call) RunAndReturn(run func(config.Action) error) *MockFirewall_SetDefaultAction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAllowlistTC provides a mock function with given fields: configMgr
func (_m *MockFirewall) UpdateAllowlistTC(configMgr *config.Manager) error {
	ret := _m.Called(configMgr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAllowlistTC")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*config.Manager) error); ok {
		r0 = rf(configMgr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFirewall_UpdateAllowlistTC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAllowlistTC'
type MockFirewall_UpdateAllowlistTC_Call struct {
	*mock.Call
}

// UpdateAllowlistTC is a helper method to define mock.On call
//   - configMgr *config.Manager
func (_e *MockFirewall_Expecter) UpdateAllowlistTC(configMgr interface{}) *MockFirewall_UpdateAllowlistTC_Call {
	return &MockFirewall_UpdateAllowlistTC_Call{Call: _e.mock.On("UpdateAllowlistTC", configMgr)}
}

func (_c *MockFirewall_UpdateAllowlistTC_Call) Run(run func(configMgr *config.Manager)) *MockFirewall_UpdateAllowlistTC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.Manager))
	})
	return _c
}

func (_c *MockFirewall_UpdateAllowlistTC_Call) Return(_a0 error) *MockFirewall_UpdateAllowlistTC_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFirewall_UpdateAllowlistTC_Call) RunAndReturn(run func(*config.Manager) error) *MockFirewall_UpdateAllowlistTC_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFirewall creates a new instance of MockFirewall. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFirewall(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFirewall {
	mock := &MockFirewall{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
