// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cargo_wall.proto

package v1

import (
	data "github.com/code-cargo/cargowall/pb/cargowall/v1/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CargoWallPolicy struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Mode          data.CargoWallMode       `protobuf:"varint,1,opt,name=mode,proto3,enum=grpc.cargowall.v1.CargoWallMode" json:"mode,omitempty"`
	DefaultAction data.CargoWallActionType `protobuf:"varint,2,opt,name=default_action,json=defaultAction,proto3,enum=grpc.cargowall.v1.CargoWallActionType" json:"default_action,omitempty"`
	Rules         []*CargoWallPolicy_Rule  `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoWallPolicy) Reset() {
	*x = CargoWallPolicy{}
	mi := &file_cargo_wall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoWallPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoWallPolicy) ProtoMessage() {}

func (x *CargoWallPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoWallPolicy.ProtoReflect.Descriptor instead.
func (*CargoWallPolicy) Descriptor() ([]byte, []int) {
	return file_cargo_wall_proto_rawDescGZIP(), []int{0}
}

func (x *CargoWallPolicy) GetMode() data.CargoWallMode {
	if x != nil {
		return x.Mode
	}
	return data.CargoWallMode(0)
}

func (x *CargoWallPolicy) GetDefaultAction() data.CargoWallActionType {
	if x != nil {
		return x.DefaultAction
	}
	return data.CargoWallActionType(0)
}

func (x *CargoWallPolicy) GetRules() []*CargoWallPolicy_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CargoWallPolicy_Rule struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          data.CargoWallRuleType   `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.cargowall.v1.CargoWallRuleType" json:"type,omitempty"`
	Value         string                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Action        data.CargoWallActionType `protobuf:"varint,3,opt,name=action,proto3,enum=grpc.cargowall.v1.CargoWallActionType" json:"action,omitempty"`
	Ports         []uint32                 `protobuf:"varint,4,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoWallPolicy_Rule) Reset() {
	*x = CargoWallPolicy_Rule{}
	mi := &file_cargo_wall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoWallPolicy_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoWallPolicy_Rule) ProtoMessage() {}

func (x *CargoWallPolicy_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoWallPolicy_Rule.ProtoReflect.Descriptor instead.
func (*CargoWallPolicy_Rule) Descriptor() ([]byte, []int) {
	return file_cargo_wall_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CargoWallPolicy_Rule) GetType() data.CargoWallRuleType {
	if x != nil {
		return x.Type
	}
	return data.CargoWallRuleType(0)
}

func (x *CargoWallPolicy_Rule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CargoWallPolicy_Rule) GetAction() data.CargoWallActionType {
	if x != nil {
		return x.Action
	}
	return data.CargoWallActionType(0)
}

func (x *CargoWallPolicy_Rule) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

var File_cargo_wall_proto protoreflect.FileDescriptor

const file_cargo_wall_proto_rawDesc = "" +
	"\n" +
	"\x10cargo_wall.proto\x12\x11grpc.cargowall.v1\x1a\x1fdata/cargo_wall_mode_enum.proto\x1a&data/cargo_wall_action_type_enum.proto\x1a$data/cargo_wall_rule_type_enum.proto\"\x84\x03\n" +
	"\x0fCargoWallPolicy\x124\n" +
	"\x04mode\x18\x01 \x01(\x0e2 .grpc.cargowall.v1.CargoWallModeR\x04mode\x12M\n" +
	"\x0edefault_action\x18\x02 \x01(\x0e2&.grpc.cargowall.v1.CargoWallActionTypeR\rdefaultAction\x12=\n" +
	"\x05rules\x18\x03 \x03(\v2'.grpc.cargowall.v1.CargoWallPolicy.RuleR\x05rules\x1a\xac\x01\n" +
	"\x04Rule\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.grpc.cargowall.v1.CargoWallRuleTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12>\n" +
	"\x06action\x18\x03 \x01(\x0e2&.grpc.cargowall.v1.CargoWallActionTypeR\x06action\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\rR\x05portsBYZ/github.com/code-cargo/cargowall/pb/cargowall/v1\xaa\x02%Controller.ApiService.Pb.CargoWall.V1b\x06proto3"

var (
	file_cargo_wall_proto_rawDescOnce sync.Once
	file_cargo_wall_proto_rawDescData []byte
)

func file_cargo_wall_proto_rawDescGZIP() []byte {
	file_cargo_wall_proto_rawDescOnce.Do(func() {
		file_cargo_wall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cargo_wall_proto_rawDesc), len(file_cargo_wall_proto_rawDesc)))
	})
	return file_cargo_wall_proto_rawDescData
}

var file_cargo_wall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cargo_wall_proto_goTypes = []any{
	(*CargoWallPolicy)(nil),       // 0: grpc.cargowall.v1.CargoWallPolicy
	(*CargoWallPolicy_Rule)(nil),  // 1: grpc.cargowall.v1.CargoWallPolicy.Rule
	(data.CargoWallMode)(0),       // 2: grpc.cargowall.v1.CargoWallMode
	(data.CargoWallActionType)(0), // 3: grpc.cargowall.v1.CargoWallActionType
	(data.CargoWallRuleType)(0),   // 4: grpc.cargowall.v1.CargoWallRuleType
}
var file_cargo_wall_proto_depIdxs = []int32{
	2, // 0: grpc.cargowall.v1.CargoWallPolicy.mode:type_name -> grpc.cargowall.v1.CargoWallMode
	3, // 1: grpc.cargowall.v1.CargoWallPolicy.default_action:type_name -> grpc.cargowall.v1.CargoWallActionType
	1, // 2: grpc.cargowall.v1.CargoWallPolicy.rules:type_name -> grpc.cargowall.v1.CargoWallPolicy.Rule
	4, // 3: grpc.cargowall.v1.CargoWallPolicy.Rule.type:type_name -> grpc.cargowall.v1.CargoWallRuleType
	3, // 4: grpc.cargowall.v1.CargoWallPolicy.Rule.action:type_name -> grpc.cargowall.v1.CargoWallActionType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cargo_wall_proto_init() }
func file_cargo_wall_proto_init() {
	if File_cargo_wall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cargo_wall_proto_rawDesc), len(file_cargo_wall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cargo_wall_proto_goTypes,
		DependencyIndexes: file_cargo_wall_proto_depIdxs,
		MessageInfos:      file_cargo_wall_proto_msgTypes,
	}.Build()
	File_cargo_wall_proto = out.File
	file_cargo_wall_proto_goTypes = nil
	file_cargo_wall_proto_depIdxs = nil
}
