// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cargo_wall_action.proto

package v1

import (
	data "github.com/code-cargo/cargowall/pb/cargowall/v1/data"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCargoWallActionJobRunPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobKey        *string                `protobuf:"bytes,1,opt,name=job_key,json=jobKey,proto3,oneof" json:"job_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCargoWallActionJobRunPolicyRequest) Reset() {
	*x = GetCargoWallActionJobRunPolicyRequest{}
	mi := &file_cargo_wall_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCargoWallActionJobRunPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCargoWallActionJobRunPolicyRequest) ProtoMessage() {}

func (x *GetCargoWallActionJobRunPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCargoWallActionJobRunPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetCargoWallActionJobRunPolicyRequest) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{0}
}

func (x *GetCargoWallActionJobRunPolicyRequest) GetJobKey() string {
	if x != nil && x.JobKey != nil {
		return *x.JobKey
	}
	return ""
}

type CargoWallActionJobSummary struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalConnections     uint32                 `protobuf:"varint,1,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	AllowedConnections   uint32                 `protobuf:"varint,2,opt,name=allowed_connections,json=allowedConnections,proto3" json:"allowed_connections,omitempty"`
	DeniedConnections    uint32                 `protobuf:"varint,3,opt,name=denied_connections,json=deniedConnections,proto3" json:"denied_connections,omitempty"`
	UniqueHostnames      uint32                 `protobuf:"varint,4,opt,name=unique_hostnames,json=uniqueHostnames,proto3" json:"unique_hostnames,omitempty"`
	WouldDenyConnections uint32                 `protobuf:"varint,5,opt,name=would_deny_connections,json=wouldDenyConnections,proto3" json:"would_deny_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CargoWallActionJobSummary) Reset() {
	*x = CargoWallActionJobSummary{}
	mi := &file_cargo_wall_action_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoWallActionJobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoWallActionJobSummary) ProtoMessage() {}

func (x *CargoWallActionJobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoWallActionJobSummary.ProtoReflect.Descriptor instead.
func (*CargoWallActionJobSummary) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{1}
}

func (x *CargoWallActionJobSummary) GetTotalConnections() uint32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *CargoWallActionJobSummary) GetAllowedConnections() uint32 {
	if x != nil {
		return x.AllowedConnections
	}
	return 0
}

func (x *CargoWallActionJobSummary) GetDeniedConnections() uint32 {
	if x != nil {
		return x.DeniedConnections
	}
	return 0
}

func (x *CargoWallActionJobSummary) GetUniqueHostnames() uint32 {
	if x != nil {
		return x.UniqueHostnames
	}
	return 0
}

func (x *CargoWallActionJobSummary) GetWouldDenyConnections() uint32 {
	if x != nil {
		return x.WouldDenyConnections
	}
	return 0
}

type CargoWallActionStep struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name          string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Number        int32                   `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	StartedAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Events        []*CargoWallActionEvent `protobuf:"bytes,100,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoWallActionStep) Reset() {
	*x = CargoWallActionStep{}
	mi := &file_cargo_wall_action_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoWallActionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoWallActionStep) ProtoMessage() {}

func (x *CargoWallActionStep) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoWallActionStep.ProtoReflect.Descriptor instead.
func (*CargoWallActionStep) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{2}
}

func (x *CargoWallActionStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CargoWallActionStep) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CargoWallActionStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CargoWallActionStep) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CargoWallActionStep) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CargoWallActionStep) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CargoWallActionStep) GetEvents() []*CargoWallActionEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CargoWallActionEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        data.CargoWallActionType    `protobuf:"varint,2,opt,name=action,proto3,enum=grpc.cargowall.v1.CargoWallActionType" json:"action,omitempty"`
	Hostname      *string                     `protobuf:"bytes,3,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	Ip            *string                     `protobuf:"bytes,4,opt,name=ip,proto3,oneof" json:"ip,omitempty"`
	Port          *uint32                     `protobuf:"varint,5,opt,name=port,proto3,oneof" json:"port,omitempty"`
	Protocol      *string                     `protobuf:"bytes,6,opt,name=protocol,proto3,oneof" json:"protocol,omitempty"`
	MatchedRule   *string                     `protobuf:"bytes,7,opt,name=matched_rule,json=matchedRule,proto3,oneof" json:"matched_rule,omitempty"`
	Process       *string                     `protobuf:"bytes,8,opt,name=process,proto3,oneof" json:"process,omitempty"`
	Category      data.CargoWallEventCategory `protobuf:"varint,9,opt,name=category,proto3,enum=grpc.cargowall.v1.CargoWallEventCategory" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CargoWallActionEvent) Reset() {
	*x = CargoWallActionEvent{}
	mi := &file_cargo_wall_action_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CargoWallActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoWallActionEvent) ProtoMessage() {}

func (x *CargoWallActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoWallActionEvent.ProtoReflect.Descriptor instead.
func (*CargoWallActionEvent) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{3}
}

func (x *CargoWallActionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CargoWallActionEvent) GetAction() data.CargoWallActionType {
	if x != nil {
		return x.Action
	}
	return data.CargoWallActionType(0)
}

func (x *CargoWallActionEvent) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *CargoWallActionEvent) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *CargoWallActionEvent) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *CargoWallActionEvent) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *CargoWallActionEvent) GetMatchedRule() string {
	if x != nil && x.MatchedRule != nil {
		return *x.MatchedRule
	}
	return ""
}

func (x *CargoWallActionEvent) GetProcess() string {
	if x != nil && x.Process != nil {
		return *x.Process
	}
	return ""
}

func (x *CargoWallActionEvent) GetCategory() data.CargoWallEventCategory {
	if x != nil {
		return x.Category
	}
	return data.CargoWallEventCategory(0)
}

type CreateCargoWallActionJobRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	JobName       string                       `protobuf:"bytes,1,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	JobKey        string                       `protobuf:"bytes,2,opt,name=job_key,json=jobKey,proto3" json:"job_key,omitempty"`
	Mode          data.CargoWallMode           `protobuf:"varint,3,opt,name=mode,proto3,enum=grpc.cargowall.v1.CargoWallMode" json:"mode,omitempty"`
	DefaultAction data.CargoWallActionType     `protobuf:"varint,4,opt,name=default_action,json=defaultAction,proto3,enum=grpc.cargowall.v1.CargoWallActionType" json:"default_action,omitempty"`
	Summary       *CargoWallActionJobSummary   `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	StartedAt     *timestamppb.Timestamp       `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp       `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Status        data.CargoWallJobStatus      `protobuf:"varint,8,opt,name=status,proto3,enum=grpc.cargowall.v1.CargoWallJobStatus" json:"status,omitempty"`
	Steps         []*CreateCargoWallActionStep `protobuf:"bytes,100,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCargoWallActionJobRequest) Reset() {
	*x = CreateCargoWallActionJobRequest{}
	mi := &file_cargo_wall_action_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCargoWallActionJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCargoWallActionJobRequest) ProtoMessage() {}

func (x *CreateCargoWallActionJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCargoWallActionJobRequest.ProtoReflect.Descriptor instead.
func (*CreateCargoWallActionJobRequest) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCargoWallActionJobRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *CreateCargoWallActionJobRequest) GetJobKey() string {
	if x != nil {
		return x.JobKey
	}
	return ""
}

func (x *CreateCargoWallActionJobRequest) GetMode() data.CargoWallMode {
	if x != nil {
		return x.Mode
	}
	return data.CargoWallMode(0)
}

func (x *CreateCargoWallActionJobRequest) GetDefaultAction() data.CargoWallActionType {
	if x != nil {
		return x.DefaultAction
	}
	return data.CargoWallActionType(0)
}

func (x *CreateCargoWallActionJobRequest) GetSummary() *CargoWallActionJobSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *CreateCargoWallActionJobRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateCargoWallActionJobRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CreateCargoWallActionJobRequest) GetStatus() data.CargoWallJobStatus {
	if x != nil {
		return x.Status
	}
	return data.CargoWallJobStatus(0)
}

func (x *CreateCargoWallActionJobRequest) GetSteps() []*CreateCargoWallActionStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

// Input-only step message (no id/created_at — server-generated)
type CreateCargoWallActionStep struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number        int32                   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	StartedAt     *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	Events        []*CargoWallActionEvent `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCargoWallActionStep) Reset() {
	*x = CreateCargoWallActionStep{}
	mi := &file_cargo_wall_action_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCargoWallActionStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCargoWallActionStep) ProtoMessage() {}

func (x *CreateCargoWallActionStep) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCargoWallActionStep.ProtoReflect.Descriptor instead.
func (*CreateCargoWallActionStep) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCargoWallActionStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCargoWallActionStep) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CreateCargoWallActionStep) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CreateCargoWallActionStep) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *CreateCargoWallActionStep) GetEvents() []*CargoWallActionEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateCargoWallActionJobResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkflowRunId  string                 `protobuf:"bytes,2,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	WorkflowRunUrl string                 `protobuf:"bytes,3,opt,name=workflow_run_url,json=workflowRunUrl,proto3" json:"workflow_run_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateCargoWallActionJobResponse) Reset() {
	*x = CreateCargoWallActionJobResponse{}
	mi := &file_cargo_wall_action_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCargoWallActionJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCargoWallActionJobResponse) ProtoMessage() {}

func (x *CreateCargoWallActionJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cargo_wall_action_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCargoWallActionJobResponse.ProtoReflect.Descriptor instead.
func (*CreateCargoWallActionJobResponse) Descriptor() ([]byte, []int) {
	return file_cargo_wall_action_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCargoWallActionJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreateCargoWallActionJobResponse) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *CreateCargoWallActionJobResponse) GetWorkflowRunUrl() string {
	if x != nil {
		return x.WorkflowRunUrl
	}
	return ""
}

var File_cargo_wall_action_proto protoreflect.FileDescriptor

const file_cargo_wall_action_proto_rawDesc = "" +
	"\n" +
	"\x17cargo_wall_action.proto\x12\x11grpc.cargowall.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&data/cargo_wall_action_type_enum.proto\x1a)data/cargo_wall_event_category_enum.proto\x1a%data/cargo_wall_job_status_enum.proto\x1a\x1fdata/cargo_wall_mode_enum.proto\x1a\x10cargo_wall.proto\"Q\n" +
	"%GetCargoWallActionJobRunPolicyRequest\x12\x1c\n" +
	"\ajob_key\x18\x01 \x01(\tH\x00R\x06jobKey\x88\x01\x01B\n" +
	"\n" +
	"\b_job_key\"\x89\x02\n" +
	"\x19CargoWallActionJobSummary\x12+\n" +
	"\x11total_connections\x18\x01 \x01(\rR\x10totalConnections\x12/\n" +
	"\x13allowed_connections\x18\x02 \x01(\rR\x12allowedConnections\x12-\n" +
	"\x12denied_connections\x18\x03 \x01(\rR\x11deniedConnections\x12)\n" +
	"\x10unique_hostnames\x18\x04 \x01(\rR\x0funiqueHostnames\x124\n" +
	"\x16would_deny_connections\x18\x05 \x01(\rR\x14wouldDenyConnections\"\xf1\x02\n" +
	"\x13CargoWallActionStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x05R\x06number\x12>\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x12?\n" +
	"\x06events\x18d \x03(\v2'.grpc.cargowall.v1.CargoWallActionEventR\x06eventsB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\xd5\x03\n" +
	"\x14CargoWallActionEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\x06action\x18\x02 \x01(\x0e2&.grpc.cargowall.v1.CargoWallActionTypeR\x06action\x12\x1f\n" +
	"\bhostname\x18\x03 \x01(\tH\x00R\bhostname\x88\x01\x01\x12\x13\n" +
	"\x02ip\x18\x04 \x01(\tH\x01R\x02ip\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x05 \x01(\rH\x02R\x04port\x88\x01\x01\x12\x1f\n" +
	"\bprotocol\x18\x06 \x01(\tH\x03R\bprotocol\x88\x01\x01\x12&\n" +
	"\fmatched_rule\x18\a \x01(\tH\x04R\vmatchedRule\x88\x01\x01\x12\x1d\n" +
	"\aprocess\x18\b \x01(\tH\x05R\aprocess\x88\x01\x01\x12E\n" +
	"\bcategory\x18\t \x01(\x0e2).grpc.cargowall.v1.CargoWallEventCategoryR\bcategoryB\v\n" +
	"\t_hostnameB\x05\n" +
	"\x03_ipB\a\n" +
	"\x05_portB\v\n" +
	"\t_protocolB\x0f\n" +
	"\r_matched_ruleB\n" +
	"\n" +
	"\b_process\"\x9f\x04\n" +
	"\x1fCreateCargoWallActionJobRequest\x12\x19\n" +
	"\bjob_name\x18\x01 \x01(\tR\ajobName\x12\x17\n" +
	"\ajob_key\x18\x02 \x01(\tR\x06jobKey\x124\n" +
	"\x04mode\x18\x03 \x01(\x0e2 .grpc.cargowall.v1.CargoWallModeR\x04mode\x12M\n" +
	"\x0edefault_action\x18\x04 \x01(\x0e2&.grpc.cargowall.v1.CargoWallActionTypeR\rdefaultAction\x12F\n" +
	"\asummary\x18\x05 \x01(\v2,.grpc.cargowall.v1.CargoWallActionJobSummaryR\asummary\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12=\n" +
	"\x06status\x18\b \x01(\x0e2%.grpc.cargowall.v1.CargoWallJobStatusR\x06status\x12B\n" +
	"\x05steps\x18d \x03(\v2,.grpc.cargowall.v1.CreateCargoWallActionStepR\x05steps\"\xac\x02\n" +
	"\x19CreateCargoWallActionStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12>\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tstartedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x12?\n" +
	"\x06events\x18\x05 \x03(\v2'.grpc.cargowall.v1.CargoWallActionEventR\x06eventsB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\x8b\x01\n" +
	" CreateCargoWallActionJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12&\n" +
	"\x0fworkflow_run_id\x18\x02 \x01(\tR\rworkflowRunId\x12(\n" +
	"\x10workflow_run_url\x18\x03 \x01(\tR\x0eworkflowRunUrl2\xf4\x02\n" +
	"\x19CargoWallActionJobService\x12\xac\x01\n" +
	"\x18CreateCargoWallActionJob\x122.grpc.cargowall.v1.CreateCargoWallActionJobRequest\x1a3.grpc.cargowall.v1.CreateCargoWallActionJobResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/cargowall/v1/action/job\x12\xa7\x01\n" +
	"\x1eGetCargoWallActionJobRunPolicy\x128.grpc.cargowall.v1.GetCargoWallActionJobRunPolicyRequest\x1a\".grpc.cargowall.v1.CargoWallPolicy\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/cargowall/v1/action/policyBYZ/github.com/code-cargo/cargowall/pb/cargowall/v1\xaa\x02%Controller.ApiService.Pb.CargoWall.V1b\x06proto3"

var (
	file_cargo_wall_action_proto_rawDescOnce sync.Once
	file_cargo_wall_action_proto_rawDescData []byte
)

func file_cargo_wall_action_proto_rawDescGZIP() []byte {
	file_cargo_wall_action_proto_rawDescOnce.Do(func() {
		file_cargo_wall_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cargo_wall_action_proto_rawDesc), len(file_cargo_wall_action_proto_rawDesc)))
	})
	return file_cargo_wall_action_proto_rawDescData
}

var file_cargo_wall_action_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cargo_wall_action_proto_goTypes = []any{
	(*GetCargoWallActionJobRunPolicyRequest)(nil), // 0: grpc.cargowall.v1.GetCargoWallActionJobRunPolicyRequest
	(*CargoWallActionJobSummary)(nil),             // 1: grpc.cargowall.v1.CargoWallActionJobSummary
	(*CargoWallActionStep)(nil),                   // 2: grpc.cargowall.v1.CargoWallActionStep
	(*CargoWallActionEvent)(nil),                  // 3: grpc.cargowall.v1.CargoWallActionEvent
	(*CreateCargoWallActionJobRequest)(nil),       // 4: grpc.cargowall.v1.CreateCargoWallActionJobRequest
	(*CreateCargoWallActionStep)(nil),             // 5: grpc.cargowall.v1.CreateCargoWallActionStep
	(*CreateCargoWallActionJobResponse)(nil),      // 6: grpc.cargowall.v1.CreateCargoWallActionJobResponse
	(*timestamppb.Timestamp)(nil),                 // 7: google.protobuf.Timestamp
	(data.CargoWallActionType)(0),                 // 8: grpc.cargowall.v1.CargoWallActionType
	(data.CargoWallEventCategory)(0),              // 9: grpc.cargowall.v1.CargoWallEventCategory
	(data.CargoWallMode)(0),                       // 10: grpc.cargowall.v1.CargoWallMode
	(data.CargoWallJobStatus)(0),                  // 11: grpc.cargowall.v1.CargoWallJobStatus
	(*CargoWallPolicy)(nil),                       // 12: grpc.cargowall.v1.CargoWallPolicy
}
var file_cargo_wall_action_proto_depIdxs = []int32{
	7,  // 0: grpc.cargowall.v1.CargoWallActionStep.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: grpc.cargowall.v1.CargoWallActionStep.started_at:type_name -> google.protobuf.Timestamp
	7,  // 2: grpc.cargowall.v1.CargoWallActionStep.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 3: grpc.cargowall.v1.CargoWallActionStep.events:type_name -> grpc.cargowall.v1.CargoWallActionEvent
	7,  // 4: grpc.cargowall.v1.CargoWallActionEvent.timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: grpc.cargowall.v1.CargoWallActionEvent.action:type_name -> grpc.cargowall.v1.CargoWallActionType
	9,  // 6: grpc.cargowall.v1.CargoWallActionEvent.category:type_name -> grpc.cargowall.v1.CargoWallEventCategory
	10, // 7: grpc.cargowall.v1.CreateCargoWallActionJobRequest.mode:type_name -> grpc.cargowall.v1.CargoWallMode
	8,  // 8: grpc.cargowall.v1.CreateCargoWallActionJobRequest.default_action:type_name -> grpc.cargowall.v1.CargoWallActionType
	1,  // 9: grpc.cargowall.v1.CreateCargoWallActionJobRequest.summary:type_name -> grpc.cargowall.v1.CargoWallActionJobSummary
	7,  // 10: grpc.cargowall.v1.CreateCargoWallActionJobRequest.started_at:type_name -> google.protobuf.Timestamp
	7,  // 11: grpc.cargowall.v1.CreateCargoWallActionJobRequest.completed_at:type_name -> google.protobuf.Timestamp
	11, // 12: grpc.cargowall.v1.CreateCargoWallActionJobRequest.status:type_name -> grpc.cargowall.v1.CargoWallJobStatus
	5,  // 13: grpc.cargowall.v1.CreateCargoWallActionJobRequest.steps:type_name -> grpc.cargowall.v1.CreateCargoWallActionStep
	7,  // 14: grpc.cargowall.v1.CreateCargoWallActionStep.started_at:type_name -> google.protobuf.Timestamp
	7,  // 15: grpc.cargowall.v1.CreateCargoWallActionStep.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 16: grpc.cargowall.v1.CreateCargoWallActionStep.events:type_name -> grpc.cargowall.v1.CargoWallActionEvent
	4,  // 17: grpc.cargowall.v1.CargoWallActionJobService.CreateCargoWallActionJob:input_type -> grpc.cargowall.v1.CreateCargoWallActionJobRequest
	0,  // 18: grpc.cargowall.v1.CargoWallActionJobService.GetCargoWallActionJobRunPolicy:input_type -> grpc.cargowall.v1.GetCargoWallActionJobRunPolicyRequest
	6,  // 19: grpc.cargowall.v1.CargoWallActionJobService.CreateCargoWallActionJob:output_type -> grpc.cargowall.v1.CreateCargoWallActionJobResponse
	12, // 20: grpc.cargowall.v1.CargoWallActionJobService.GetCargoWallActionJobRunPolicy:output_type -> grpc.cargowall.v1.CargoWallPolicy
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cargo_wall_action_proto_init() }
func file_cargo_wall_action_proto_init() {
	if File_cargo_wall_action_proto != nil {
		return
	}
	file_cargo_wall_proto_init()
	file_cargo_wall_action_proto_msgTypes[0].OneofWrappers = []any{}
	file_cargo_wall_action_proto_msgTypes[2].OneofWrappers = []any{}
	file_cargo_wall_action_proto_msgTypes[3].OneofWrappers = []any{}
	file_cargo_wall_action_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cargo_wall_action_proto_rawDesc), len(file_cargo_wall_action_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cargo_wall_action_proto_goTypes,
		DependencyIndexes: file_cargo_wall_action_proto_depIdxs,
		MessageInfos:      file_cargo_wall_action_proto_msgTypes,
	}.Build()
	File_cargo_wall_action_proto = out.File
	file_cargo_wall_action_proto_goTypes = nil
	file_cargo_wall_action_proto_depIdxs = nil
}
