// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OriginBpfL7FlowKey struct {
	_         structs.HostLayout
	Cookie    uint64
	Dst       [16]uint8
	DstPort   uint16
	IpProto   uint8
	IpVersion uint8
}

type OriginBpfL7FlowVal struct {
	_           structs.HostLayout
	State       uint8
	Punts       uint8
	LastPuntLen uint16
	LastPuntSeq uint32
	Ts          uint64
	DcidLen     uint8
	Dcid        [20]uint8
}

type OriginBpfLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        uint32
}

type OriginBpfLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        [16]uint8
}

type OriginBpfLpmVal struct {
	_            structs.HostLayout
	Action       uint8
	PortSpecific uint8
	Pad          uint16
}

type OriginBpfOriginSeenKey struct {
	_         structs.HostLayout
	Cookie    uint64
	Dst       [16]uint8
	DstPort   uint16
	IpProto   uint8
	IpVersion uint8
}

type OriginBpfOriginSeenVal struct {
	_        structs.HostLayout
	LastEmit uint64
	Verdict  uint8
	Pad      [7]uint8
}

type OriginBpfPortKey struct {
	_     structs.HostLayout
	Ip    uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type OriginBpfPortKeyV6 struct {
	_     structs.HostLayout
	Ip    [16]uint8
	Port  uint16
	Proto uint8
	Pad   uint8
}

type OriginBpfPortVal struct {
	_      structs.HostLayout
	Action uint8
	Pad    [3]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	OriginBpfMapMapAuditMode         = "map_audit_mode"
	OriginBpfMapMapCidrs             = "map_cidrs"
	OriginBpfMapMapCidrsV6           = "map_cidrs_v6"
	OriginBpfMapMapDefaultAction     = "map_default_action"
	OriginBpfMapMapL7Events          = "map_l7_events"
	OriginBpfMapMapL7Flow            = "map_l7_flow"
	OriginBpfMapMapL7Scope           = "map_l7_scope"
	OriginBpfMapMapL7ScopeV6         = "map_l7_scope_v6"
	OriginBpfMapMapL7Stats           = "map_l7_stats"
	OriginBpfMapMapLocalNets         = "map_local_nets"
	OriginBpfMapMapLocalNetsV6       = "map_local_nets_v6"
	OriginBpfMapMapOriginConfig      = "map_origin_config"
	OriginBpfMapMapOriginEvents      = "map_origin_events"
	OriginBpfMapMapOriginSeen        = "map_origin_seen"
	OriginBpfMapMapPorts             = "map_ports"
	OriginBpfMapMapPortsV6           = "map_ports_v6"
	OriginBpfProgCgOriginEgress      = "cg_origin_egress"
	OriginBpfVarBtfAnchorL7Event     = "btf_anchor_l7_event"
	OriginBpfVarBtfAnchorOriginEvent = "btf_anchor_origin_event"
)

// LoadOriginBpf returns the embedded CollectionSpec for OriginBpf.
func LoadOriginBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OriginBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load OriginBpf: %w", err)
	}

	return spec, err
}

// LoadOriginBpfObjects loads OriginBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OriginBpfObjects
//	*OriginBpfPrograms
//	*OriginBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOriginBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOriginBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OriginBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfSpecs struct {
	OriginBpfProgramSpecs
	OriginBpfMapSpecs
	OriginBpfVariableSpecs
}

// OriginBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfProgramSpecs struct {
	CgOriginEgress *ebpf.ProgramSpec `ebpf:"cg_origin_egress"`
}

// OriginBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfMapSpecs struct {
	MapAuditMode     *ebpf.MapSpec `ebpf:"map_audit_mode"`
	MapCidrs         *ebpf.MapSpec `ebpf:"map_cidrs"`
	MapCidrsV6       *ebpf.MapSpec `ebpf:"map_cidrs_v6"`
	MapDefaultAction *ebpf.MapSpec `ebpf:"map_default_action"`
	MapL7Events      *ebpf.MapSpec `ebpf:"map_l7_events"`
	MapL7Flow        *ebpf.MapSpec `ebpf:"map_l7_flow"`
	MapL7Scope       *ebpf.MapSpec `ebpf:"map_l7_scope"`
	MapL7ScopeV6     *ebpf.MapSpec `ebpf:"map_l7_scope_v6"`
	MapL7Stats       *ebpf.MapSpec `ebpf:"map_l7_stats"`
	MapLocalNets     *ebpf.MapSpec `ebpf:"map_local_nets"`
	MapLocalNetsV6   *ebpf.MapSpec `ebpf:"map_local_nets_v6"`
	MapOriginConfig  *ebpf.MapSpec `ebpf:"map_origin_config"`
	MapOriginEvents  *ebpf.MapSpec `ebpf:"map_origin_events"`
	MapOriginSeen    *ebpf.MapSpec `ebpf:"map_origin_seen"`
	MapPorts         *ebpf.MapSpec `ebpf:"map_ports"`
	MapPortsV6       *ebpf.MapSpec `ebpf:"map_ports_v6"`
}

// OriginBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfVariableSpecs struct {
	BtfAnchorL7Event     *ebpf.VariableSpec `ebpf:"btf_anchor_l7_event"`
	BtfAnchorOriginEvent *ebpf.VariableSpec `ebpf:"btf_anchor_origin_event"`
}

// OriginBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfObjects struct {
	OriginBpfPrograms
	OriginBpfMaps
	OriginBpfVariables
}

func (o *OriginBpfObjects) Close() error {
	return _OriginBpfClose(
		&o.OriginBpfPrograms,
		&o.OriginBpfMaps,
	)
}

// OriginBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfMaps struct {
	MapAuditMode     *ebpf.Map `ebpf:"map_audit_mode"`
	MapCidrs         *ebpf.Map `ebpf:"map_cidrs"`
	MapCidrsV6       *ebpf.Map `ebpf:"map_cidrs_v6"`
	MapDefaultAction *ebpf.Map `ebpf:"map_default_action"`
	MapL7Events      *ebpf.Map `ebpf:"map_l7_events"`
	MapL7Flow        *ebpf.Map `ebpf:"map_l7_flow"`
	MapL7Scope       *ebpf.Map `ebpf:"map_l7_scope"`
	MapL7ScopeV6     *ebpf.Map `ebpf:"map_l7_scope_v6"`
	MapL7Stats       *ebpf.Map `ebpf:"map_l7_stats"`
	MapLocalNets     *ebpf.Map `ebpf:"map_local_nets"`
	MapLocalNetsV6   *ebpf.Map `ebpf:"map_local_nets_v6"`
	MapOriginConfig  *ebpf.Map `ebpf:"map_origin_config"`
	MapOriginEvents  *ebpf.Map `ebpf:"map_origin_events"`
	MapOriginSeen    *ebpf.Map `ebpf:"map_origin_seen"`
	MapPorts         *ebpf.Map `ebpf:"map_ports"`
	MapPortsV6       *ebpf.Map `ebpf:"map_ports_v6"`
}

func (m *OriginBpfMaps) Close() error {
	return _OriginBpfClose(
		m.MapAuditMode,
		m.MapCidrs,
		m.MapCidrsV6,
		m.MapDefaultAction,
		m.MapL7Events,
		m.MapL7Flow,
		m.MapL7Scope,
		m.MapL7ScopeV6,
		m.MapL7Stats,
		m.MapLocalNets,
		m.MapLocalNetsV6,
		m.MapOriginConfig,
		m.MapOriginEvents,
		m.MapOriginSeen,
		m.MapPorts,
		m.MapPortsV6,
	)
}

// OriginBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfVariables struct {
	BtfAnchorL7Event     *ebpf.Variable `ebpf:"btf_anchor_l7_event"`
	BtfAnchorOriginEvent *ebpf.Variable `ebpf:"btf_anchor_origin_event"`
}

// OriginBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfPrograms struct {
	CgOriginEgress *ebpf.Program `ebpf:"cg_origin_egress"`
}

func (p *OriginBpfPrograms) Close() error {
	return _OriginBpfClose(
		p.CgOriginEgress,
	)
}

func _OriginBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed originbpf_bpfeb.o
var _OriginBpfBytes []byte
