// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OriginBpfOriginSeenKey struct {
	_         structs.HostLayout
	Cookie    uint64
	Dst       [16]uint8
	DstPort   uint16
	IpProto   uint8
	IpVersion uint8
}

// LoadOriginBpf returns the embedded CollectionSpec for OriginBpf.
func LoadOriginBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OriginBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load OriginBpf: %w", err)
	}

	return spec, err
}

// LoadOriginBpfObjects loads OriginBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OriginBpfObjects
//	*OriginBpfPrograms
//	*OriginBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOriginBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOriginBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OriginBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfSpecs struct {
	OriginBpfProgramSpecs
	OriginBpfMapSpecs
	OriginBpfVariableSpecs
}

// OriginBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfProgramSpecs struct {
	CgOriginEgress *ebpf.ProgramSpec `ebpf:"cg_origin_egress"`
}

// OriginBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfMapSpecs struct {
	MapOriginEvents *ebpf.MapSpec `ebpf:"map_origin_events"`
	MapOriginSeen   *ebpf.MapSpec `ebpf:"map_origin_seen"`
}

// OriginBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OriginBpfVariableSpecs struct {
	BtfAnchorOriginEvent *ebpf.VariableSpec `ebpf:"btf_anchor_origin_event"`
}

// OriginBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfObjects struct {
	OriginBpfPrograms
	OriginBpfMaps
	OriginBpfVariables
}

func (o *OriginBpfObjects) Close() error {
	return _OriginBpfClose(
		&o.OriginBpfPrograms,
		&o.OriginBpfMaps,
	)
}

// OriginBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfMaps struct {
	MapOriginEvents *ebpf.Map `ebpf:"map_origin_events"`
	MapOriginSeen   *ebpf.Map `ebpf:"map_origin_seen"`
}

func (m *OriginBpfMaps) Close() error {
	return _OriginBpfClose(
		m.MapOriginEvents,
		m.MapOriginSeen,
	)
}

// OriginBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfVariables struct {
	BtfAnchorOriginEvent *ebpf.Variable `ebpf:"btf_anchor_origin_event"`
}

// OriginBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOriginBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type OriginBpfPrograms struct {
	CgOriginEgress *ebpf.Program `ebpf:"cg_origin_egress"`
}

func (p *OriginBpfPrograms) Close() error {
	return _OriginBpfClose(
		p.CgOriginEgress,
	)
}

func _OriginBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed originbpf_bpfeb.o
var _OriginBpfBytes []byte
