// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type StepBpfStepState struct {
	_           structs.HostLayout
	WorkerTgid  uint32
	Enabled     uint32
	NextOrdinal uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	StepBpfMapMapSockStep             = "map_sock_step"
	StepBpfMapMapStepEvents           = "map_step_events"
	StepBpfMapMapStepState            = "map_step_state"
	StepBpfMapMapTaskStep             = "map_task_step"
	StepBpfProgCgSockCreate           = "cg_sock_create"
	StepBpfProgStepExit               = "step_exit"
	StepBpfProgStepFork               = "step_fork"
	StepBpfVarBtfAnchorStepChildEvent = "btf_anchor_step_child_event"
)

// LoadStepBpf returns the embedded CollectionSpec for StepBpf.
func LoadStepBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StepBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load StepBpf: %w", err)
	}

	return spec, err
}

// LoadStepBpfObjects loads StepBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*StepBpfObjects
//	*StepBpfPrograms
//	*StepBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadStepBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadStepBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// StepBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StepBpfSpecs struct {
	StepBpfProgramSpecs
	StepBpfMapSpecs
	StepBpfVariableSpecs
}

// StepBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StepBpfProgramSpecs struct {
	CgSockCreate *ebpf.ProgramSpec `ebpf:"cg_sock_create"`
	StepExit     *ebpf.ProgramSpec `ebpf:"step_exit"`
	StepFork     *ebpf.ProgramSpec `ebpf:"step_fork"`
}

// StepBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StepBpfMapSpecs struct {
	MapSockStep   *ebpf.MapSpec `ebpf:"map_sock_step"`
	MapStepEvents *ebpf.MapSpec `ebpf:"map_step_events"`
	MapStepState  *ebpf.MapSpec `ebpf:"map_step_state"`
	MapTaskStep   *ebpf.MapSpec `ebpf:"map_task_step"`
}

// StepBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StepBpfVariableSpecs struct {
	BtfAnchorStepChildEvent *ebpf.VariableSpec `ebpf:"btf_anchor_step_child_event"`
}

// StepBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadStepBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type StepBpfObjects struct {
	StepBpfPrograms
	StepBpfMaps
	StepBpfVariables
}

func (o *StepBpfObjects) Close() error {
	return _StepBpfClose(
		&o.StepBpfPrograms,
		&o.StepBpfMaps,
	)
}

// StepBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadStepBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type StepBpfMaps struct {
	MapSockStep   *ebpf.Map `ebpf:"map_sock_step"`
	MapStepEvents *ebpf.Map `ebpf:"map_step_events"`
	MapStepState  *ebpf.Map `ebpf:"map_step_state"`
	MapTaskStep   *ebpf.Map `ebpf:"map_task_step"`
}

func (m *StepBpfMaps) Close() error {
	return _StepBpfClose(
		m.MapSockStep,
		m.MapStepEvents,
		m.MapStepState,
		m.MapTaskStep,
	)
}

// StepBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadStepBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type StepBpfVariables struct {
	BtfAnchorStepChildEvent *ebpf.Variable `ebpf:"btf_anchor_step_child_event"`
}

// StepBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadStepBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type StepBpfPrograms struct {
	CgSockCreate *ebpf.Program `ebpf:"cg_sock_create"`
	StepExit     *ebpf.Program `ebpf:"step_exit"`
	StepFork     *ebpf.Program `ebpf:"step_fork"`
}

func (p *StepBpfPrograms) Close() error {
	return _StepBpfClose(
		p.CgSockCreate,
		p.StepExit,
		p.StepFork,
	)
}

func _StepBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stepbpf_bpfeb.o
var _StepBpfBytes []byte
