// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcBpfLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        uint32
}

type TcBpfLpmKeyV6 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Ip        [16]uint8
}

type TcBpfLpmVal struct {
	_            structs.HostLayout
	Action       uint8
	PortSpecific uint8
	Pad          uint16
}

type TcBpfPortKey struct {
	_     structs.HostLayout
	Ip    uint32
	Port  uint16
	Proto uint8
	Pad   uint8
}

type TcBpfPortKeyV6 struct {
	_     structs.HostLayout
	Ip    [16]uint8
	Port  uint16
	Proto uint8
	Pad   uint8
}

type TcBpfPortVal struct {
	_      structs.HostLayout
	Action uint8
	Pad    [3]uint8
}

// LoadTcBpf returns the embedded CollectionSpec for TcBpf.
func LoadTcBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load TcBpf: %w", err)
	}

	return spec, err
}

// LoadTcBpfObjects loads TcBpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcBpfObjects
//	*TcBpfPrograms
//	*TcBpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTcBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcBpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcBpfSpecs struct {
	TcBpfProgramSpecs
	TcBpfMapSpecs
	TcBpfVariableSpecs
}

// TcBpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcBpfProgramSpecs struct {
	CgConnect4 *ebpf.ProgramSpec `ebpf:"cg_connect4"`
	CgConnect6 *ebpf.ProgramSpec `ebpf:"cg_connect6"`
	CgSendmsg4 *ebpf.ProgramSpec `ebpf:"cg_sendmsg4"`
	CgSendmsg6 *ebpf.ProgramSpec `ebpf:"cg_sendmsg6"`
	TcEgress   *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress  *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// TcBpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcBpfMapSpecs struct {
	MapAuditMode     *ebpf.MapSpec `ebpf:"map_audit_mode"`
	MapCidrs         *ebpf.MapSpec `ebpf:"map_cidrs"`
	MapCidrsV6       *ebpf.MapSpec `ebpf:"map_cidrs_v6"`
	MapDefaultAction *ebpf.MapSpec `ebpf:"map_default_action"`
	MapEvents        *ebpf.MapSpec `ebpf:"map_events"`
	MapPorts         *ebpf.MapSpec `ebpf:"map_ports"`
	MapPortsV6       *ebpf.MapSpec `ebpf:"map_ports_v6"`
	MapSockPid       *ebpf.MapSpec `ebpf:"map_sock_pid"`
}

// TcBpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcBpfVariableSpecs struct {
}

// TcBpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcBpfObjects struct {
	TcBpfPrograms
	TcBpfMaps
	TcBpfVariables
}

func (o *TcBpfObjects) Close() error {
	return _TcBpfClose(
		&o.TcBpfPrograms,
		&o.TcBpfMaps,
	)
}

// TcBpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcBpfMaps struct {
	MapAuditMode     *ebpf.Map `ebpf:"map_audit_mode"`
	MapCidrs         *ebpf.Map `ebpf:"map_cidrs"`
	MapCidrsV6       *ebpf.Map `ebpf:"map_cidrs_v6"`
	MapDefaultAction *ebpf.Map `ebpf:"map_default_action"`
	MapEvents        *ebpf.Map `ebpf:"map_events"`
	MapPorts         *ebpf.Map `ebpf:"map_ports"`
	MapPortsV6       *ebpf.Map `ebpf:"map_ports_v6"`
	MapSockPid       *ebpf.Map `ebpf:"map_sock_pid"`
}

func (m *TcBpfMaps) Close() error {
	return _TcBpfClose(
		m.MapAuditMode,
		m.MapCidrs,
		m.MapCidrsV6,
		m.MapDefaultAction,
		m.MapEvents,
		m.MapPorts,
		m.MapPortsV6,
		m.MapSockPid,
	)
}

// TcBpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcBpfVariables struct {
}

// TcBpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcBpfPrograms struct {
	CgConnect4 *ebpf.Program `ebpf:"cg_connect4"`
	CgConnect6 *ebpf.Program `ebpf:"cg_connect6"`
	CgSendmsg4 *ebpf.Program `ebpf:"cg_sendmsg4"`
	CgSendmsg6 *ebpf.Program `ebpf:"cg_sendmsg6"`
	TcEgress   *ebpf.Program `ebpf:"tc_egress"`
	TcIngress  *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *TcBpfPrograms) Close() error {
	return _TcBpfClose(
		p.CgConnect4,
		p.CgConnect6,
		p.CgSendmsg4,
		p.CgSendmsg6,
		p.TcEgress,
		p.TcIngress,
	)
}

func _TcBpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcbpf_bpfel.o
var _TcBpfBytes []byte
