//   Copyright 2026 BoxBuild Inc DBA CodeCargo
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

//go:build linux

package lockdown

import (
	"encoding/json"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateSudoersInput(t *testing.T) {
	tests := []struct {
		name      string
		username  string
		cmds      []string
		wantErr   bool
		errSubstr string
	}{
		{
			name:     "valid username and commands",
			username: "runner",
			cmds:     []string{"/usr/bin/kill", "/usr/bin/iptables"},
		},
		{
			name:      "username with space",
			username:  "bad user",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with semicolon",
			username:  "user;rm",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with backtick",
			username:  "user`id`",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with newline",
			username:  "user\nroot ALL=(ALL) ALL",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with hash",
			username:  "user#comment",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "command with space",
			username:  "runner",
			cmds:      []string{"/usr/bin/my command"},
			wantErr:   true,
			errSubstr: "command",
		},
		{
			name:      "command with semicolon",
			username:  "runner",
			cmds:      []string{"/usr/bin/kill;rm -rf /"},
			wantErr:   true,
			errSubstr: "command",
		},
		{
			name:      "empty username returns error",
			username:  "",
			cmds:      []string{"/usr/bin/kill"},
			wantErr:   true,
			errSubstr: "empty",
		},
		{
			name:     "empty commands slice is valid",
			username: "runner",
			cmds:     nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := validateSudoersInput(tt.username, tt.cmds)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				if !strings.Contains(err.Error(), tt.errSubstr) {
					t.Errorf("error %q should contain %q", err.Error(), tt.errSubstr)
				}
			} else {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
			}
		})
	}
}

func TestBuildSudoersConfig(t *testing.T) {
	tests := []struct {
		name         string
		cfg          *SudoLockdownConfig
		username     string
		wantErr      bool
		wantContains []string
		wantAbsent   string
	}{
		{
			name: "single allowed command",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "runner",
			wantContains: []string{
				"/usr/sbin/iptables",
				"runner ALL=(ALL) NOPASSWD:",
			},
		},
		{
			name: "multiple allowed commands comma-separated",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables", "/usr/sbin/ip6tables"},
			},
			username: "runner",
			wantContains: []string{
				"runner ALL=(ALL) NOPASSWD: /usr/sbin/iptables, /usr/sbin/ip6tables",
			},
		},
		{
			name:     "empty allow commands produces no grant line",
			cfg:      &SudoLockdownConfig{},
			username: "runner",
			wantContains: []string{
				"# CargoWall sudo lockdown configuration",
			},
			wantAbsent: "NOPASSWD",
		},
		{
			name: "unsafe username returns error",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "bad;user",
			wantErr:  true,
		},
		{
			name: "output format matches expected sudoers structure",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "ci",
			wantContains: []string{
				"# CargoWall sudo lockdown configuration",
				"# Generated by cargowall - DO NOT EDIT",
				"ci ALL=(ALL) NOPASSWD: /usr/sbin/iptables\n",
			},
		},
		{
			name: "header mentions disabled files",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "runner",
			wantContains: []string{
				disabledSuffix,
				"sudo-granting groups",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := buildSudoersConfig(tt.cfg, tt.username)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			for _, s := range tt.wantContains {
				if !strings.Contains(got, s) {
					t.Errorf("output should contain %q\ngot:\n%s", s, got)
				}
			}

			if tt.wantAbsent != "" && strings.Contains(got, tt.wantAbsent) {
				t.Errorf("output should NOT contain %q\ngot:\n%s", tt.wantAbsent, got)
			}
		})
	}
}

func TestSudoersFileGrantsUser(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		username string
		want     bool
		wantErr  bool
	}{
		{
			name:     "direct grant matches",
			content:  "runner ALL=(ALL) NOPASSWD:ALL\n",
			username: "runner",
			want:     true,
		},
		{
			name:     "grant with tab separator",
			content:  "runner\tALL=(ALL) NOPASSWD:ALL\n",
			username: "runner",
			want:     true,
		},
		{
			name:     "comment line ignored",
			content:  "# runner ALL=(ALL) NOPASSWD:ALL\n",
			username: "runner",
			want:     false,
		},
		{
			name:     "different user no match",
			content:  "admin ALL=(ALL) NOPASSWD:ALL\n",
			username: "runner",
			want:     false,
		},
		{
			name:     "group grant matches when GIDs unknown (fail-closed)",
			content:  "%sudo ALL=(ALL:ALL) ALL\n",
			username: "runner",
			want:     true, // nil GIDs = any %group is a potential grant
		},
		{
			name:     "empty file",
			content:  "",
			username: "runner",
			want:     false,
		},
		{
			name:     "username as substring does not match",
			content:  "runner2 ALL=(ALL) ALL\n",
			username: "runner",
			want:     false,
		},
		{
			name: "match among multiple lines",
			content: `# Defaults
Defaults env_reset
runner ALL=(ALL) NOPASSWD:ALL
`,
			username: "runner",
			want:     true,
		},
		{
			name:     "User_Alias with target user matches",
			content:  "User_Alias RUNNERS = runner, admin\nRUNNERS ALL=(ALL) ALL\n",
			username: "runner",
			want:     true,
		},
		{
			name:     "User_Alias without target user does not match",
			content:  "User_Alias ADMINS = admin, root\nADMINS ALL=(ALL) ALL\n",
			username: "runner",
			want:     false,
		},
		{
			name:     "User_Alias single user",
			content:  "User_Alias CI = runner\nCI ALL=(ALL) NOPASSWD:ALL\n",
			username: "runner",
			want:     true,
		},
		{
			name:     "User_Alias with inline comment",
			content:  "User_Alias CI = runner # CI user\nCI ALL=(ALL) ALL\n",
			username: "runner",
			want:     true,
		},
		{
			name:     "hash include directive returns error",
			content:  "#include /etc/sudoers.d/extra\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "hash includedir directive returns error",
			content:  "#includedir /etc/sudoers.d/extra.d\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "at-include directive returns error",
			content:  "@include /etc/sudoers.d/extra\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "at-includedir directive returns error",
			content:  "@includedir /etc/sudoers.d/extra.d\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "Defaults !authenticate returns error",
			content:  "Defaults !authenticate\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "Defaults with authenticate negation in context returns error",
			content:  "Defaults:runner !authenticate\n",
			username: "runner",
			wantErr:  true,
		},
		{
			name:     "group grant matches when GIDs nil (fail-closed)",
			content:  "%ops ALL=(ALL) ALL\n",
			username: "runner",
			want:     true, // nil GIDs = treat any %group as potential grant
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "sudoers")
			if err := os.WriteFile(path, []byte(tt.content), 0o644); err != nil {
				t.Fatal(err)
			}
			got, err := sudoersFileGrantsUser(path, tt.username, nil, nil)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != tt.want {
				t.Errorf("sudoersFileGrantsUser() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestSudoersFileGrantsUser_unreadableFile(t *testing.T) {
	_, err := sudoersFileGrantsUser("/nonexistent/path", "runner", nil, nil)
	if err == nil {
		t.Fatal("expected error for unreadable file, got nil")
	}
}

func TestDisableCompetingSudoersFiles(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	// Create files that grant the user access
	writeFile(t, filepath.Join(dir, "90-runner"), "runner ALL=(ALL) NOPASSWD:ALL\n")
	writeFile(t, filepath.Join(dir, "50-cloud-init"), "# cloud-init defaults\nDefaults env_reset\n")
	writeFile(t, filepath.Join(dir, "91-other"), "otheruser ALL=(ALL) ALL\n")

	disabled, err := disableCompetingSudoersFiles(dir, "runner", logger)
	if err != nil {
		t.Fatal(err)
	}

	if len(disabled) != 1 {
		t.Fatalf("expected 1 disabled file, got %d: %v", len(disabled), disabled)
	}
	if filepath.Base(disabled[0]) != "90-runner" {
		t.Errorf("expected 90-runner to be disabled, got %s", disabled[0])
	}

	// Verify the file was renamed
	if _, err := os.Stat(filepath.Join(dir, "90-runner")); !os.IsNotExist(err) {
		t.Error("original file should not exist after disable")
	}
	if _, err := os.Stat(filepath.Join(dir, "90-runner"+disabledSuffix)); err != nil {
		t.Error("disabled file should exist")
	}

	// Non-matching files should be untouched
	if _, err := os.Stat(filepath.Join(dir, "50-cloud-init")); err != nil {
		t.Error("non-matching file should be untouched")
	}
	if _, err := os.Stat(filepath.Join(dir, "91-other")); err != nil {
		t.Error("other user file should be untouched")
	}
}

func TestDisableCompetingSudoersFiles_skipsOwnFiles(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	// Create our own files — they should never be disabled
	writeFile(t, filepath.Join(dir, filepath.Base(sudoersFile)), "runner ALL=(ALL) NOPASSWD: /usr/sbin/iptables\n")
	writeFile(t, filepath.Join(dir, filepath.Base(stateFile)), `{"username":"runner"}`)

	disabled, err := disableCompetingSudoersFiles(dir, "runner", logger)
	if err != nil {
		t.Fatal(err)
	}
	if len(disabled) != 0 {
		t.Errorf("expected 0 disabled files, got %d: %v", len(disabled), disabled)
	}
}

func TestRestoreDisabledSudoersFiles(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	original := filepath.Join(dir, "90-runner")
	disabledPath := original + disabledSuffix
	writeFile(t, disabledPath, "runner ALL=(ALL) NOPASSWD:ALL\n")

	if ok := restoreDisabledSudoersFiles([]string{original}, logger); !ok {
		t.Error("restoreDisabledSudoersFiles should return true on success")
	}

	if _, err := os.Stat(original); err != nil {
		t.Error("original file should be restored")
	}
	if _, err := os.Stat(disabledPath); !os.IsNotExist(err) {
		t.Error("disabled file should not exist after restore")
	}
}

func TestRestoreDisabledSudoersFiles_toleratesMissing(t *testing.T) {
	logger := discardLogger()
	// Should not panic or error on missing files; missing disabled file is tolerated
	if ok := restoreDisabledSudoersFiles([]string{"/nonexistent/file"}, logger); !ok {
		t.Error("restoreDisabledSudoersFiles should return true for missing files (tolerated)")
	}
}

// TestLockdownStateJSONRoundTrip verifies JSON round-trip of lockdownState.
// The real saveLockdownState/loadLockdownState functions use atomic write
// (tmp+rename) and file permissions, which are exercised by the CI
// integration test (test-sudo-lockdown).
func TestLockdownStateJSONRoundTrip(t *testing.T) {
	state := &lockdownState{
		Username:      "runner",
		RemovedGroups: []string{"sudo", "wheel"},
		DisabledFiles: []string{"/etc/sudoers.d/90-runner"},
		DockerRemoved: true,
	}

	data, err := json.Marshal(state)
	if err != nil {
		t.Fatal(err)
	}

	var loaded lockdownState
	if err := json.Unmarshal(data, &loaded); err != nil {
		t.Fatal(err)
	}

	if loaded.Username != state.Username {
		t.Errorf("username: got %q, want %q", loaded.Username, state.Username)
	}
	if len(loaded.RemovedGroups) != len(state.RemovedGroups) {
		t.Errorf("removedGroups length: got %d, want %d", len(loaded.RemovedGroups), len(state.RemovedGroups))
	}
	if len(loaded.DisabledFiles) != len(state.DisabledFiles) {
		t.Errorf("disabledFiles length: got %d, want %d", len(loaded.DisabledFiles), len(state.DisabledFiles))
	}
	if loaded.DockerRemoved != state.DockerRemoved {
		t.Errorf("dockerRemoved: got %v, want %v", loaded.DockerRemoved, state.DockerRemoved)
	}
}

func TestUserAliasContains(t *testing.T) {
	tests := []struct {
		name     string
		line     string
		username string
		want     bool
	}{
		{
			name:     "exact match",
			line:     "User_Alias CI = runner",
			username: "runner",
			want:     true,
		},
		{
			name:     "among multiple members",
			line:     "User_Alias RUNNERS = admin, runner, ci",
			username: "runner",
			want:     true,
		},
		{
			name:     "not present",
			line:     "User_Alias ADMINS = admin, root",
			username: "runner",
			want:     false,
		},
		{
			name:     "substring does not match",
			line:     "User_Alias CI = runner2, runner3",
			username: "runner",
			want:     false,
		},
		{
			name:     "no equals sign",
			line:     "User_Alias BROKEN",
			username: "runner",
			want:     false,
		},
		{
			name:     "empty after equals",
			line:     "User_Alias EMPTY = ",
			username: "runner",
			want:     false,
		},
		{
			name:     "inline comment stripped",
			line:     "User_Alias CI = runner # the CI user",
			username: "runner",
			want:     true,
		},
		{
			name:     "inline comment hides member",
			line:     "User_Alias CI = admin # runner",
			username: "runner",
			want:     false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := userAliasContains(tt.line, tt.username); got != tt.want {
				t.Errorf("userAliasContains() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestSudoersFileGrantsUser_crossFileAlias(t *testing.T) {
	// A file containing only "RUNNERS ALL=(ALL) ALL" should be detected as a
	// grant when we know (from another file) that RUNNERS is a User_Alias
	// containing our target user.
	path := filepath.Join(t.TempDir(), "sudoers")
	writeFile(t, path, "RUNNERS ALL=(ALL) ALL\n")

	// Without aliases — should NOT match
	got, err := sudoersFileGrantsUser(path, "runner", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got {
		t.Error("should not match without aliases")
	}

	// With aliases — should match
	aliases := map[string]bool{"RUNNERS": true}
	got, err = sudoersFileGrantsUser(path, "runner", nil, aliases)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !got {
		t.Error("should match when RUNNERS is a known alias for the user")
	}
}

func TestCollectUserAliases(t *testing.T) {
	dir := t.TempDir()

	// File with alias containing target user
	writeFile(t, filepath.Join(dir, "10-aliases"), "User_Alias RUNNERS = runner, admin\n")
	// File with alias NOT containing target user
	writeFile(t, filepath.Join(dir, "20-other"), "User_Alias ADMINS = admin, root\n")
	// File with grant using the alias
	writeFile(t, filepath.Join(dir, "30-grant"), "RUNNERS ALL=(ALL) ALL\n")

	aliases := collectUserAliases(dir, "runner")
	if !aliases["RUNNERS"] {
		t.Error("expected RUNNERS in aliases")
	}
	if aliases["ADMINS"] {
		t.Error("ADMINS should not be in aliases (runner is not a member)")
	}
}

func TestCollectUserAliases_skipsOwnFiles(t *testing.T) {
	dir := t.TempDir()

	// Our own files should be skipped even if they match
	writeFile(t, filepath.Join(dir, filepath.Base(sudoersFile)), "User_Alias CI = runner\n")
	writeFile(t, filepath.Join(dir, filepath.Base(stateFile)), "User_Alias CI = runner\n")
	writeFile(t, filepath.Join(dir, "test.tmp"), "User_Alias CI = runner\n")
	writeFile(t, filepath.Join(dir, "test"+disabledSuffix), "User_Alias CI = runner\n")

	aliases := collectUserAliases(dir, "runner")
	if len(aliases) != 0 {
		t.Errorf("expected no aliases from own files, got %v", aliases)
	}
}

func TestUserAliasName(t *testing.T) {
	tests := []struct {
		line string
		want string
	}{
		{"User_Alias RUNNERS = runner, admin", "RUNNERS"},
		{"User_Alias CI = runner", "CI"},
		{"User_Alias BROKEN", ""},
		{"User_Alias", ""},
	}
	for _, tt := range tests {
		if got := userAliasName(tt.line); got != tt.want {
			t.Errorf("userAliasName(%q) = %q, want %q", tt.line, got, tt.want)
		}
	}
}

func TestDisableCompetingSudoersFiles_crossFileAlias(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	// Alias defined in one file, grant using it in another
	writeFile(t, filepath.Join(dir, "10-aliases"), "User_Alias RUNNERS = runner, admin\n")
	writeFile(t, filepath.Join(dir, "20-grant"), "RUNNERS ALL=(ALL) ALL\n")
	// Unrelated file
	writeFile(t, filepath.Join(dir, "30-other"), "otheruser ALL=(ALL) ALL\n")

	disabled, err := disableCompetingSudoersFiles(dir, "runner", logger)
	if err != nil {
		t.Fatal(err)
	}

	// Both the alias file and the grant file should be disabled
	if len(disabled) != 2 {
		t.Fatalf("expected 2 disabled files, got %d: %v", len(disabled), disabled)
	}

	// Verify the files were renamed
	if _, err := os.Stat(filepath.Join(dir, "10-aliases")); !os.IsNotExist(err) {
		t.Error("alias file should be disabled")
	}
	if _, err := os.Stat(filepath.Join(dir, "20-grant")); !os.IsNotExist(err) {
		t.Error("grant file should be disabled")
	}
	// Unrelated file untouched
	if _, err := os.Stat(filepath.Join(dir, "30-other")); err != nil {
		t.Error("unrelated file should be untouched")
	}
}

func TestFindDisabledSudoersFiles(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	writeFile(t, filepath.Join(dir, "90-runner"+disabledSuffix), "runner ALL=(ALL) ALL\n")
	writeFile(t, filepath.Join(dir, "50-other"+disabledSuffix), "other ALL=(ALL) ALL\n")
	writeFile(t, filepath.Join(dir, "normal-file"), "something\n")

	found := findDisabledSudoersFiles(dir, logger)
	if len(found) != 2 {
		t.Fatalf("expected 2 disabled files, got %d: %v", len(found), found)
	}
}

func TestFindDisabledSudoersFiles_emptyDir(t *testing.T) {
	dir := t.TempDir()
	logger := discardLogger()

	found := findDisabledSudoersFiles(dir, logger)
	if len(found) != 0 {
		t.Errorf("expected 0 disabled files, got %d", len(found))
	}
}

func TestValidateSudoersInput_rejectsWildcards(t *testing.T) {
	// Wildcards in sudoers command paths could grant unintended access
	for _, cmd := range []string{"/usr/bin/*", "/usr/bin/apt?", "/usr/bin/[a-z]"} {
		if err := validateSudoersInput("runner", []string{cmd}); err == nil {
			t.Errorf("expected error for wildcard command %q, got nil", cmd)
		}
	}
}

// helpers

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func discardLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, nil))
}
