//   Copyright 2026 BoxBuild Inc DBA CodeCargo
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

//go:build linux

package lockdown

import (
	"strings"
	"testing"
)

func TestValidateSudoersInput(t *testing.T) {
	tests := []struct {
		name      string
		username  string
		cmds      []string
		wantErr   bool
		errSubstr string
	}{
		{
			name:     "valid username and commands",
			username: "runner",
			cmds:     []string{"/usr/bin/kill", "/usr/bin/iptables"},
		},
		{
			name:      "username with space",
			username:  "bad user",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with semicolon",
			username:  "user;rm",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with backtick",
			username:  "user`id`",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with newline",
			username:  "user\nroot ALL=(ALL) ALL",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "username with hash",
			username:  "user#comment",
			cmds:      nil,
			wantErr:   true,
			errSubstr: "username",
		},
		{
			name:      "command with space",
			username:  "runner",
			cmds:      []string{"/usr/bin/my command"},
			wantErr:   true,
			errSubstr: "command",
		},
		{
			name:      "command with semicolon",
			username:  "runner",
			cmds:      []string{"/usr/bin/kill;rm -rf /"},
			wantErr:   true,
			errSubstr: "command",
		},
		{
			name:     "empty username is valid",
			username: "",
			cmds:     []string{"/usr/bin/kill"},
		},
		{
			name:     "empty commands slice is valid",
			username: "runner",
			cmds:     nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := validateSudoersInput(tt.username, tt.cmds)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				if !strings.Contains(err.Error(), tt.errSubstr) {
					t.Errorf("error %q should contain %q", err.Error(), tt.errSubstr)
				}
			} else {
				if err != nil {
					t.Fatalf("unexpected error: %v", err)
				}
			}
		})
	}
}

func TestBuildSudoersConfig(t *testing.T) {
	tests := []struct {
		name          string
		cfg           *SudoLockdownConfig
		username      string
		wantErr       bool
		wantContains  []string
		wantExactLine string // if set, output must contain this exact line
	}{
		{
			name: "single allowed command includes kill",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "runner",
			wantContains: []string{
				"/usr/sbin/iptables",
				"/usr/bin/kill",
				"runner ALL=(ALL) NOPASSWD:",
			},
		},
		{
			name: "multiple allowed commands comma-separated with kill at end",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables", "/usr/sbin/ip6tables"},
			},
			username:      "runner",
			wantExactLine: "runner ALL=(ALL) NOPASSWD: /usr/sbin/iptables, /usr/sbin/ip6tables, /usr/bin/kill",
		},
		{
			name:          "empty allow commands only has kill",
			cfg:           &SudoLockdownConfig{},
			username:      "runner",
			wantExactLine: "runner ALL=(ALL) NOPASSWD: /usr/bin/kill",
		},
		{
			name: "unsafe username returns error",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/bin/kill"},
			},
			username: "bad;user",
			wantErr:  true,
		},
		{
			name: "output format matches expected sudoers structure",
			cfg: &SudoLockdownConfig{
				AllowCommands: []string{"/usr/sbin/iptables"},
			},
			username: "ci",
			wantContains: []string{
				"# CargoWall sudo lockdown configuration",
				"# Generated by cargowall - DO NOT EDIT",
				"ci ALL=(ALL) NOPASSWD: /usr/sbin/iptables, /usr/bin/kill\n",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := buildSudoersConfig(tt.cfg, tt.username)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			for _, s := range tt.wantContains {
				if !strings.Contains(got, s) {
					t.Errorf("output should contain %q\ngot:\n%s", s, got)
				}
			}

			if tt.wantExactLine != "" && !strings.Contains(got, tt.wantExactLine) {
				t.Errorf("output should contain exact line %q\ngot:\n%s", tt.wantExactLine, got)
			}
		})
	}
}
